# Author: Behnam <b.farnaghi@gmail.com>
# AI-assisted implementation; manually reviewed and verified by the developer.
# Generated by Django 5.2.17 on 2026-08-14 15:25

import django.core.validators
import web.models
import web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_stripewebhookevent_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetpreference',
            name='danger_gif',
            field=models.FileField(blank=True, upload_to=web.models.dashboard_animation_upload_to, validators=[django.core.validators.FileExtensionValidator(['gif']), web.validators.validate_dashboard_gif]),
        ),
        migrations.AddField(
            model_name='budgetpreference',
            name='healthy_gif',
            field=models.FileField(blank=True, upload_to=web.models.dashboard_animation_upload_to, validators=[django.core.validators.FileExtensionValidator(['gif']), web.validators.validate_dashboard_gif]),
        ),
        migrations.AddField(
            model_name='budgetpreference',
            name='warning_gif',
            field=models.FileField(blank=True, upload_to=web.models.dashboard_animation_upload_to, validators=[django.core.validators.FileExtensionValidator(['gif']), web.validators.validate_dashboard_gif]),
        ),
    ]
